'use strict';
const path=require('node:path'),fs=require('node:fs');const {setPublicId}=require('../src/moderation.cjs');const {openStore,transaction}=require('../src/store.cjs');
const data=path.resolve(process.env.DATA_DIR||path.join(__dirname,'../data'));const db=openStore(path.join(data,'zoigram.sqlite'));const [command,id,...reasonParts]=process.argv.slice(2),reason=reasonParts.join(' ');
(async()=>{
 if(command==='set-id'){const [newId,...parts]=reasonParts;console.log(JSON.stringify(setPublicId(db,id,newId,parts.join(' ')),null,2));return}
 if(command==='profiles'){const query=(id||'').replace(/^@/,'');console.log(JSON.stringify(db.prepare('SELECT id,username,display_name,banned FROM profiles WHERE ?=\'\' OR instr(lower(username),lower(?))>0 OR id=? ORDER BY created_at DESC LIMIT 100').all(query,query,query),null,2));return}
 if(command==='reports'){console.log(JSON.stringify(db.prepare('SELECT id,kind,target_id,reason,created_at,resolved FROM reports WHERE resolved=0 ORDER BY id LIMIT 100').all(),null,2));return}
 if(command==='stats'){console.log(JSON.stringify({profiles:db.prepare('SELECT COUNT(*) n FROM profiles').get().n,posts:db.prepare('SELECT COUNT(*) n FROM posts').get().n,bytes:db.prepare('SELECT COALESCE(SUM(bytes),0) n FROM posts').get().n},null,2));return}
 if(command==='backup'){console.log(JSON.stringify(await require('../src/backups.cjs').createBackup(data,path.resolve(process.env.BACKUP_DIR||path.join(__dirname,'../backups')),{keep:Number(process.env.BACKUP_KEEP||3)}),null,2));return}
 if(!['ban','unban','delete-post','delete-comment','resolve'].includes(command)||!id||!reason)throw Error('Usage: node tools/admin.cjs reports | stats | backup | profiles [SEARCH] | set-id UUID_OR_@ID NEW_ID REASON | ban|unban|delete-post|delete-comment|resolve ID REASON');
 transaction(db,()=>{let result;if(command==='ban'||command==='unban'){result=db.prepare('UPDATE profiles SET banned=? WHERE id=?').run(command==='ban'?1:0,id);if(command==='ban')db.prepare('DELETE FROM sessions WHERE profile_id=?').run(id)}if(command==='delete-post')result=db.prepare('DELETE FROM posts WHERE id=?').run(Number(id));if(command==='delete-comment')result=db.prepare('DELETE FROM comments WHERE id=?').run(Number(id));if(command==='resolve')result=db.prepare('UPDATE reports SET resolved=1 WHERE id=?').run(Number(id));if(!result.changes)throw Error('Target not found');db.prepare('INSERT INTO moderation(action,target_id,reason,created_at) VALUES(?,?,?,?)').run(command,id,reason,Date.now())});console.log('Done.');
})().catch(e=>{console.error(e.message);process.exitCode=1}).finally(()=>db.close());

