/* Owner operations console. Server data and announcement text are rendered as text only. */
window.ZoigramOperations={mount(parent,context){
 'use strict';
 const {api,el,button,count,badge,date,modal,toast,route,filter={}}=context;
 let disposed=false,sequence=0,controller,timer,ownedForm;
 const status=el('p',{class:'operations-updated',role:'status'}),error=el('div',{class:'error-box',role:'alert',hidden:''}),content=el('div');
 const size=value=>Number.isFinite(value)?value>=1073741824?(value/1073741824).toFixed(2)+' ГиБ':value>=1048576?(value/1048576).toFixed(1)+' МиБ':Math.ceil(value/1024)+' КиБ':'Нет данных';
 const when=value=>Number.isFinite(value)&&Number.isFinite(new Date(value).getTime())?date(value):'Нет данных';
 const percent=(used,total)=>Number.isFinite(used)&&Number.isFinite(total)&&total>0?Math.min(100,Math.max(0,used/total*100)):null;
 const kinds={info:'Информация',update:'Обновление',maintenance:'Технические работы'};
 const warnings={media_quota:['Место для фото заканчивается','Медиа и незавершённые загрузки заняли не менее 80% квоты Zoigram. Освободите место или увеличьте квоту с учётом свободного диска.'],disk_low:['Мало места на диске','Свободно менее 10% диска или менее 1 ГиБ. Проверьте резервные копии и другие файлы сервера.'],memory_high:['Высокая нагрузка на память','Контейнер использует более 85% выделенной памяти. Проверьте параллельные загрузки и лимит памяти.'],backup_attention:['Проверьте резервное копирование','Сведения о копиях недоступны, устарели или последняя попытка завершилась ошибкой.'],restore_attention:['Проверьте восстановление копии','Нет успешной проверки восстановления за последние восемь дней.']};
 const errors={photo_read:['Не прочитана фотография','Попросите игрока заново сохранить снимок в фоторежиме и повторить загрузку.'],photo_prepare:['Не удалось подготовить фотографию','Проверьте версию мода и формат снимка; игроку поможет новая фотография.'],photo_size:['Слишком большая фотография','Проверьте версию мода: актуальный клиент уменьшает снимки перед загрузкой.'],network:['Соединение прервано','Игрок может повторить загрузку; уже принятые фотографии сохраняются на сервере.'],response:['Неверный ответ сервера','Сопоставьте время с серверными ошибками и проверьте доступность API.'],rate_limit:['Слишком много запросов','Нужно дождаться снятия временного ограничения и повторить запрос.'],storage_full:['Место для фото заполнено','Проверьте квоту и свободный диск в разделе «Сервер».'],busy:['Сервер занят','Запрос можно повторить позже. Проверьте активные загрузки и память.'],server_error:['Внутренняя ошибка сервера','Проверьте состояние сервера и причину сбоя по этому времени.'],conflict:['Конфликт запроса','Обновите данные и повторите действие. Незавершённый альбом повторно отправляется из черновика.'],request_rejected:['Запрос отклонён','Проверьте код HTTP, размер снимка и версию мода.']};
 parent.append(status,error,content);
 function live(){return !disposed&&parent.isConnected;}
 function progress(label,used,total){const value=percent(used,total),bar=el('div',{class:'meter',role:'meter','aria-label':label,'aria-valuemin':0,'aria-valuemax':100,'aria-valuenow':value===null?0:Math.round(value),'aria-valuetext':value===null?'Нет данных':value.toFixed(1)+'%'});const fill=el('div');fill.style.width=(value||0)+'%';bar.append(fill);return bar;}
 function details(pairs){return el('dl',{class:'operations-data'},pairs.flatMap(([label,value])=>[el('dt',{},label),el('dd',{},value)]));}
 function panel(title,...children){return el('section',{class:'panel operations-panel'},el('h2',{},title),...children);}
 function duration(seconds){return !Number.isFinite(seconds)?'Нет данных':seconds>=86400?Math.floor(seconds/86400)+' д. '+Math.floor(seconds%86400/3600)+' ч.':seconds>=3600?Math.floor(seconds/3600)+' ч. '+Math.floor(seconds%3600/60)+' мин.':Math.floor(seconds/60)+' мин.';}
 async function request(path,render){
  if(!live())return;if(controller)controller.abort();controller=new AbortController();const current=++sequence;error.hidden=true;status.textContent='Загружаем данные…';
  try{const data=await api(path,{signal:controller.signal});if(!live()||current!==sequence)return;render(data);status.textContent='Обновлено '+when(data.at||Date.now())+(route==='operations'?' · автообновление каждые 30 секунд':'');}
  catch(e){if(e.name==='AbortError'||!live()||current!==sequence)return;error.textContent=e.message||'Не удалось получить данные.';error.hidden=false;status.textContent='Данные не обновлены. Нажмите «Обновить», чтобы повторить запрос.';}
 }
 function renderBackups(backups={}){
  if(!backups.available)return panel('Резервные копии',badge('Нет сведений','red'),el('p',{},'Сервер не получил состояние службы резервного копирования. Это не означает, что копий нет: проверьте запуск службы и подключение каталога копий.'));
  const lastError=backups.lastError,restore=backups.lastRestoreTest,restoreFresh=restore?.ok&&Date.now()-restore.at<=8*86400000;
  const backupCodes={backup_failed:'Создание копии завершилось ошибкой',restore_failed:'Проверка восстановления завершилась ошибкой',status_unavailable:'Не удалось прочитать сведения о копиях'};
  const lastIssue=lastError?(backupCodes[lastError.code]||'Ошибка службы резервного копирования')+' · '+when(lastError.at):'Ошибок последней попытки нет';
  const restoreState=!restore?'Проверка ещё не выполнена':(restore.ok?'Проверка пройдена':'Проверка не пройдена')+' · '+when(restore.at);
  return panel('Резервные копии',el('div',{class:'inline'},badge(backups.inProgress?'Создаётся копия':lastError?'Нужна проверка':backups.stale?'Копия устарела':'Копии актуальны',lastError||backups.stale?'red':backups.inProgress?'':'green'),badge(restoreFresh?'Восстановление проверено':restore?.ok?'Проверка восстановления устарела':'Нужна проверка восстановления',restoreFresh?'green':'gray')),details([
   ['Последняя успешная копия',when(backups.lastSuccessAt)],['Последняя попытка',when(backups.lastAttemptAt)],['Следующая копия',when(backups.nextDueAt)],['Интервал',duration(backups.intervalSeconds)],['Размер последней копии',size(backups.lastBackup?.bytes)],['Результат последней попытки',lastIssue],['Последняя проверка восстановления',restoreState],...(Number.isFinite(restore?.durationMs)?[['Длительность проверки',(restore.durationMs/1000).toFixed(1)+' сек.']]:[])
  ]),el('p',{class:'muted'},'Проверка восстановления выполняется отдельно от рабочей базы. Состояние здесь обновляется после запуска службы резервного копирования.'));
 }
 function renderOperations(data){
  const storage=data.storage||{},memory=data.memory||{},container=memory.container||{},disk=data.disk,uploads=data.uploads||{},notices=el('div',{class:'operations-notices'});
  for(const code of data.warnings||[]){const entry=warnings[code];if(entry)notices.append(el('div',{class:'operations-warning',role:'status'},el('b',{},entry[0]),el('p',{},entry[1])));}
  const stats=el('div',{class:'stats operations-stats'},[['Обработка фотографий',count(uploads.active)+' / '+count(uploads.maximum),'Одновременно обрабатываются'],['Незавершённые альбомы',count(uploads.pending),'Ждут продолжения или завершения'],['Ошибок за 24 часа',count(data.errors24h),'Подробности в разделе «Ошибки»'],['Версия сервера',data.version||'Нет данных','Работает '+duration(data.uptimeSeconds)]].map(([title,value,note])=>el('div',{class:'stat'},el('span',{class:'stat-label'},title),el('span',{class:'stat-value'},value),el('span',{class:'stat-note'},note))));
  const media=panel('Квота Zoigram',el('div',{class:'storage-number'},size(storage.media),el('small',{},' / '+size(storage.quota))),progress('Квота медиа с незавершёнными загрузками',(storage.media||0)+(storage.staged||0),storage.quota),details([['Опубликованные фото и аватары',size(storage.media)],['Незавершённые загрузки',size(storage.staged)],['Осталось в квоте',Number.isFinite(storage.quota)?size(Math.max(0,storage.quota-(storage.media||0)-(storage.staged||0))):'Нет данных'],['База данных и служебные файлы',size(storage.databaseBytes)]]),el('p',{},'Квота ограничивает медиа Zoigram. Это отдельный лимит приложения, а не объём диска VPS.'));
  const diskPanel=panel('Диск сервера',el('div',{class:'storage-number'},disk?size(disk.free):'Нет данных',el('small',{},' свободно')),disk?progress('Занято на диске',disk.total-disk.free,disk.total):null,details([['Полный объём файловой системы',size(disk?.total)],['Занято на диске',disk?size(disk.total-disk.free):'Нет данных']]),el('p',{},'Данные файловой системы, в которой хранится база Zoigram. Здесь также учитываются другие файлы и сервисы на этом диске.'));
  const memoryPanel=panel('Память',details([['Контейнер · используется',size(container.used)],['Контейнер · лимит',size(container.limit)],['Процесс Zoigram · используется',size(memory.rss)],['Хост · всего RAM',size(memory.hostTotal)],['Хост · свободно RAM',size(memory.hostFree)]]),container.limit?progress('Память контейнера',container.used,container.limit):null,el('p',{},'Лимит контейнера и оперативная память хоста показаны отдельно. Если лимит контейнера не задан или недоступен, отображается «Нет данных».'));
  const cpu=data.cpu||{},load=Array.isArray(cpu.load)?cpu.load.slice(0,3).map(n=>Number.isFinite(n)?n.toFixed(2):'—').join(' / '):'Нет данных';
  const loadPanel=panel('Нагрузка',details([['Доступных процессорных ядер',count(cpu.cores)],['Средняя нагрузка · 1 / 5 / 15 мин.',load],['Время работы процесса',duration(data.uptimeSeconds)]]),el('p',{},'Средняя нагрузка — число задач, ожидающих процессор или ввод-вывод; это не процент загрузки CPU.'));
  content.replaceChildren(notices,stats,el('div',{class:'operations-grid'},media,diskPanel,memoryPanel,loadPanel),renderBackups(data.backups));
 }
 let errorItems=[],cursor=null,errorBusy=false;
 const sourceNames={server:'Сервер',client:'Мод'},routeNames={upload:'Загрузка фото',api:'API',auth:'Вход',media:'Просмотр фото'};
 function renderErrors(){
  const source=el('select',{id:'operations-error-source','aria-label':'Источник ошибки'},[['','Все источники'],['server','Сервер'],['client','Мод']].map(([value,label])=>el('option',{value},label)));source.value=filter.source||'';source.addEventListener('change',()=>{filter.source=source.value;fetchErrors();});
  const toolbar=el('div',{class:'toolbar'},el('div',{class:'operations-filter'},el('label',{for:'operations-error-source'},'Источник'),source),el('small',{},'Последние 14 дней · до 5 000 записей'));
  const list=el('div',{class:'list'});
  for(const item of errorItems){const definition=errors[item.code]||['Запрос завершился ошибкой','Проверьте состояние сервера и повторите действие.'];list.append(el('article',{class:'panel operations-error'},el('div',{class:'report-top'},el('div',{class:'inline'},badge(sourceNames[item.source]||'Неизвестно'),badge(item.status?'HTTP '+item.status:'До ответа сервера','gray'),el('small',{},routeNames[item.route]||'Запрос')),el('small',{},when(item.created_at))),el('h2',{},definition[0]),el('p',{},definition[1]),details([['Игрок',item.username?'@'+item.username:item.profile_id?'Профиль удалён':'Не определён'],['Версия мода',item.client_version&&item.client_version!=='unknown'?item.client_version:'Не указана'],['Размер фотографии',size(item.image_bytes)],['Номер события',String(item.id)]])));}
  if(!errorItems.length)list.append(el('div',{class:'empty'},el('h2',{},'Ошибок по этому фильтру нет'),el('p',{},'Здесь появятся причины отклонённых запросов и сообщения о загрузке от новых версий мода.')));
  const more=cursor?button(errorBusy?'Загружаем…':'Показать ещё',()=>fetchErrors(true)):null;if(more)more.disabled=errorBusy;
  content.replaceChildren(toolbar,list,...(more?[el('div',{class:'more'},more)]:[]));
 }
 async function fetchErrors(more=false){if(errorBusy&&more)return;errorBusy=true;if(more)renderErrors();const params=new URLSearchParams();if(filter.source)params.set('source',filter.source);if(more&&cursor)params.set('before',cursor);await request('api/errors?'+params,data=>{errorItems=more?[...errorItems,...data.items]:data.items;cursor=data.nextCursor;errorBusy=false;renderErrors();});errorBusy=false;if(live()){const moreButton=content.querySelector('.more button');if(moreButton){moreButton.disabled=false;moreButton.textContent='Показать ещё';}}}
 function announcementState(item){const now=Date.now();return !item.active?['Скрыто','gray']:item.endsAt!==null&&item.endsAt<=now?['Завершено','gray']:item.startsAt>now?['Запланировано','']:['Показывается','green'];}
 function announcementPreview(item){return el('article',{class:'announcement-preview'},el('div',{class:'inline'},badge(kinds[item.kind]||kinds.info),badge(...announcementState(item))),el('h3',{},item.title||'Заголовок объявления'),el('p',{},item.body||'Текст, который увидят игроки.'));}
 function renderAnnouncements(data){
  const items=data.items||[],list=el('div',{class:'list'});
  for(const item of items){const toggle=button(item.active?'Скрыть':'Включить',async()=>{toggle.disabled=true;try{await api('api/announcements',{method:'POST',body:{id:item.id,expectedRevision:item.revision,title:item.title,body:item.body,kind:item.kind,active:!item.active,startsAt:item.startsAt,endsAt:item.endsAt}});if(live()){toast(item.active?'Объявление скрыто.':'Объявление включено с указанным расписанием.');await refreshAnnouncements();}}finally{toggle.disabled=false;}},item.active?'ghost small':'primary small');list.append(el('article',{class:'panel announcement-card'},announcementPreview(item),details([['Начало показа',when(item.startsAt)],['Конец показа',item.endsAt===null?'Без срока':when(item.endsAt)],['Изменено',when(item.updatedAt)]]),el('div',{class:'row-actions'},button('Редактировать',()=>editAnnouncement(item),'ghost small'),toggle)));}
  if(!items.length)list.append(el('div',{class:'empty'},el('h2',{},'Объявлений пока нет'),el('p',{},'Создайте сообщение об обновлении или технических работах для игроков.')));
  content.replaceChildren(el('div',{class:'toolbar'},el('p',{class:'muted'},'Игроки с поддерживающей версией мода видят до трёх активных объявлений. Время указано в часовом поясе браузера.'),button('Новое объявление',()=>editAnnouncement(),'primary')),list);
 }
 function localInput(value){if(!Number.isFinite(value))return '';const d=new Date(value),pad=n=>String(n).padStart(2,'0');return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())+'T'+pad(d.getHours())+':'+pad(d.getMinutes());}
 function editAnnouncement(existing){
  if(!live())return;const initial=existing||{title:'',body:'',kind:'info',active:true,startsAt:Date.now(),endsAt:null},view=modal(existing?'Редактировать объявление':'Новое объявление'),form=el('form',{id:'operations-announcement-form'}),fieldset=el('fieldset',{class:'announcement-fields'});ownedForm=form;
  const title=el('input',{id:'announcement-title',name:'title',required:'',maxlength:80,value:initial.title}),body=el('textarea',{id:'announcement-body',name:'body',required:'',maxlength:1200,rows:6},initial.body),kind=el('select',{id:'announcement-kind',name:'kind'},Object.entries(kinds).map(([value,label])=>el('option',{value},label))),active=el('input',{id:'announcement-active',name:'active',type:'checkbox'}),starts=el('input',{id:'announcement-start',name:'startsAt',type:'datetime-local',required:'',value:localInput(initial.startsAt)}),ends=el('input',{id:'announcement-end',name:'endsAt',type:'datetime-local',value:localInput(initial.endsAt)});
  kind.value=initial.kind;active.checked=initial.active;
  const originalStart=starts.value,originalEnd=ends.value,formError=el('div',{class:'error-box',role:'alert',hidden:''}),preview=el('div',{'aria-label':'Предпросмотр объявления'}),counter=el('small',{id:'announcement-count'}),submit=el('button',{class:'button primary',type:'submit',form:'operations-announcement-form'},'Сохранить');
  const label=(text,input)=>el('div',{class:'announcement-field'},el('label',{class:'field-label',for:input.id},text),input);
  body.setAttribute('aria-describedby','announcement-count');
  const timeValue=(input,original,value)=>input.value===original?value:input.value?new Date(input.value).getTime():null;
  function values(){return {title:title.value,body:body.value,kind:kind.value,active:active.checked,startsAt:timeValue(starts,originalStart,initial.startsAt),endsAt:timeValue(ends,originalEnd,initial.endsAt)};}
  function updatePreview(){counter.textContent=[...body.value].length+' / 1 200 символов';preview.replaceChildren(el('h3',{class:'announcement-preview-label'},'Предпросмотр'),announcementPreview(values()));}
  fieldset.append(label('Заголовок',title),label('Текст',body),counter,label('Тип сообщения',kind),el('div',{class:'announcement-schedule'},label('Начало показа',starts),label('Конец показа · необязательно',ends)),el('small',{},'Часовой пояс: '+Intl.DateTimeFormat().resolvedOptions().timeZone+'. Пустой конец — без ограничения по времени.'),el('label',{class:'announcement-checkbox',for:'announcement-active'},active,'Включено'),preview);
  form.append(formError,fieldset);form.addEventListener('input',updatePreview);form.addEventListener('change',updatePreview);
  form.addEventListener('submit',async event=>{event.preventDefault();if(submit.disabled||!live())return;formError.hidden=true;const value=values();if(!value.title.trim()||!value.body.trim()){formError.textContent='Введите заголовок и текст объявления.';formError.hidden=false;return;}if(!Number.isSafeInteger(value.startsAt)||value.startsAt<0||value.endsAt!==null&&(!Number.isSafeInteger(value.endsAt)||value.endsAt<=value.startsAt)){formError.textContent='Конец показа должен быть позже начала.';formError.hidden=false;return;}if(existing){value.id=existing.id;value.expectedRevision=existing.revision;}submit.disabled=true;fieldset.disabled=true;
   try{await api('api/announcements',{method:'POST',body:value});if(!live())return;const dialog=form.closest('dialog');if(dialog?.open)dialog.close();toast('Объявление сохранено.');await refreshAnnouncements();}
   catch(e){if(!live())return;formError.textContent=e.message||'Не удалось сохранить объявление.';formError.hidden=false;formError.scrollIntoView({block:'nearest'});}
   finally{submit.disabled=false;fieldset.disabled=false;}
  });view.body.append(form);view.footer.append(button('Отмена',()=>form.closest('dialog')?.close()),submit);updatePreview();title.focus();
 }
 function refreshAnnouncements(){return request('api/announcements',renderAnnouncements);}
 if(route==='operations'){request('api/operations',renderOperations);timer=setInterval(()=>{if(!document.hidden)request('api/operations',renderOperations);},30000);}
 else if(route==='errors')fetchErrors();else refreshAnnouncements();
 return function stop(){disposed=true;sequence++;if(timer)clearInterval(timer);if(controller)controller.abort();const dialog=ownedForm?.closest('dialog');if(dialog?.open)dialog.close();};
}};
