/* Read-only ZoiMeet monitoring. Uses the existing owner session on this origin. */
window.ZoiMeetModeration={mount(parent,{api,el,button,count,badge,date,filter}){
 let disposed=false,sequence=0,busy=false,controller,last=null;
 const code=value=>value.slice(0,5)+' '+value.slice(5),summary=el('div',{class:'stats zoimeet-stats'}),message=el('p',{class:'zoimeet-update',role:'status'}),error=el('div',{class:'error-box',role:'alert',hidden:''}),data=el('div');
 const search=el('input',{type:'search',value:filter.q||'',placeholder:'Код игрока','aria-label':'Код игрока',maxlength:20}),searchForm=el('form',{class:'search',onsubmit:e=>{e.preventDefault();filter.q=search.value.trim();filter.devicePage=1;filter.requestPage=1;refresh();}},search,el('button',{class:'button ghost',type:'submit'},'Найти'));
 const chips=el('div',{class:'chips','aria-label':'Подключения'});for(const [key,label]of [['online','На связи'],['all','Все устройства']])chips.append(button(label,()=>{filter.status=key;filter.devicePage=1;refresh();},(filter.status||'online')===key?'active':''));
 parent.append(el('div',{class:'panel zoimeet-note'},el('p',{},'Здесь видны подключения к серверу ZoiMeet и приглашения. Общие игровые сессии пока не создаются.'),el('small',{},'«На связи» — приложение обращалось к серверу за последние 20 секунд. Имена из Zoigram не привязываются к кодам.')),summary,el('div',{class:'toolbar'},searchForm,chips),message,error,data);
 function pager(section,result,key){if(result.pages<=1)return;section.append(el('div',{class:'between zoimeet-pages'},button('Назад',()=>{filter[key]=Math.max(1,result.page-1);refresh();}),el('small',{},'Страница '+result.page+' из '+result.pages),button('Далее',()=>{filter[key]=Math.min(result.pages,result.page+1);refresh();})));const buttons=section.querySelectorAll('.zoimeet-pages button');buttons[0].disabled=result.page<=1;buttons[1].disabled=result.page>=result.pages;}
 function render(result){
  summary.replaceChildren(...[['На связи',result.summary.online],['Устройств',result.summary.registered],['Ждут ответа',result.summary.pending],['Приглашение принято',result.summary.accepted]].map(([name,value])=>el('div',{class:'stat'},el('span',{class:'stat-label'},name),el('span',{class:'stat-value'},count(value)))));
  const players=el('section',{class:'zoimeet-section'},el('h2',{},'Подключения · '+count(result.devices.total)));
  if(!result.devices.items.length)players.append(el('p',{class:'panel muted'},'Подключений по этому фильтру нет.'));else players.append(el('div',{class:'table-wrap'},el('table',{},el('thead',{},el('tr',{},['Код','Статус','Клиент','Версия ZoiMeet','Последняя связь'].map(s=>el('th',{},s)))),el('tbody',{},result.devices.items.map(d=>el('tr',{},el('td',{class:'nowrap'},el('b',{},code(d.code))),el('td',{},badge(d.online?'На связи':'Не в сети',d.online?'green':'')),el('td',{},d.client==='game'?'inZOI':'Браузер',d.gameBuild?el('small',{class:'zoimeet-build'},d.gameBuild):null),el('td',{},d.modVersion),el('td',{class:'muted nowrap'},date(d.lastSeen))))))));pager(players,result.devices,'devicePage');
  const requests=el('section',{class:'zoimeet-section'},el('h2',{},'Активные приглашения · '+count(result.requests.total)));
  if(!result.requests.items.length)requests.append(el('p',{class:'panel muted'},'Активных приглашений нет.'));else requests.append(el('div',{class:'table-wrap'},el('table',{},el('thead',{},el('tr',{},['Пригласил','Приглашён','Статус','Отправлено','Действует до'].map(s=>el('th',{},s)))),el('tbody',{},result.requests.items.map(i=>el('tr',{},el('td',{class:'nowrap'},code(i.hostCode),el('small',{class:'zoimeet-build'},i.hostOnline?'На связи':'Не в сети')),el('td',{class:'nowrap'},code(i.guestCode),el('small',{class:'zoimeet-build'},i.guestOnline?'На связи':'Не в сети')),el('td',{},badge(i.status==='accepted'?'Приглашение принято':'Ждёт ответа',i.status==='accepted'?'green':'')),el('td',{class:'muted nowrap'},date(i.createdAt)),el('td',{class:'muted nowrap'},date(i.expiresAt))))))));pager(requests,result.requests,'requestPage');
  data.replaceChildren(players,requests);last=result.serverTime;message.textContent='Обновлено '+date(last)+' · автообновление каждые 10 секунд';Array.from(chips.children).forEach((b,i)=>b.classList.toggle('active',(filter.status||'online')===(i?'all':'online')));
 }
 async function refresh(automatic=false){
  if(disposed||!parent.isConnected){stop();return;}if(automatic&&(busy||document.hidden))return;
  if(controller)controller.abort();controller=new AbortController();const current=++sequence;busy=true;error.hidden=true;if(!last)message.textContent='Загружаем подключения ZoiMeet…';
  try{const params=new URLSearchParams({status:filter.status||'online',q:filter.q||'',devicePage:filter.devicePage||1,requestPage:filter.requestPage||1});const result=await api('api/zoimeet?'+params,{signal:controller.signal});if(current!==sequence||disposed||!parent.isConnected)return;render(result);}catch(e){if(e.name==='AbortError'||disposed||current!==sequence)return;error.textContent=e.message;error.hidden=false;message.textContent=last?'Связь потеряна. Показаны данные на '+date(last)+'.':'Не удалось получить сведения ZoiMeet.';}finally{if(current===sequence)busy=false;}
 }
 const timer=setInterval(()=>refresh(true),10000);function stop(){disposed=true;sequence++;clearInterval(timer);if(controller)controller.abort();}
 refresh();return stop;
}};
