'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),vm=require('node:vm');
const {createApp}=require('../src/app.cjs'),{identity,session,random,hash}=require('../src/store.cjs');
const OWNER='76561198000000001',OTHER='76561198000000002',origin='https://zoigram.example';
async function fixture(t,options={}){
 const app=createApp({database:':memory:',origin,secret:Buffer.alloc(32,7),ownerSteamId:OWNER,...options});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>app.close());
 const owner=identity(app.db,'steam',OWNER),other=identity(app.db,'steam',OTHER),token=random(),adminId=crypto.randomUUID();app.db.prepare('INSERT INTO admin_sessions VALUES(?,?,?,?)').run(adminId,hash(token),owner.id,Date.now()+3600000);const cookie='__Host-zoigram_admin='+token;
 const request=(p,options={})=>fetch('http://127.0.0.1:'+app.server.address().port+p,{redirect:'manual',...options});const bootstrap=await(await request('/admin/api/session',{headers:{Cookie:cookie}})).json();
 async function call(p,{body,headers={},method=body?'POST':'GET'}={}){const r=await request(p,{method,headers:{Cookie:cookie,Origin:origin,'Content-Type':'application/json','X-CSRF-Token':bootstrap.csrfToken||'',...headers},body:body?JSON.stringify(body):undefined});const data=(r.headers.get('content-type')||'').includes('application/json')?await r.json():await r.text();return {status:r.status,data,headers:r.headers}}
 function post(p=other){return Number(app.db.prepare('INSERT INTO posts(profile_id,request_id,payload_hash,caption,created_at,width,height,image,thumbnail,bytes) VALUES(?,?,?,?,?,?,?,?,?,?)').run(p.id,random(),'digest','<script>alert(1)</script> 🌆',Date.now(),64,64,Buffer.from('photo'),Buffer.from('thumbnail'),14).lastInsertRowid)}
 return {app,owner,other,cookie,request,call,post,adminId};
}
test('private data never accepts anonymous, game Bearer tokens or other accounts',async t=>{
 const f=await fixture(t),id=f.post(),game=session(f.app.db,f.owner.id);for(const p of ['/admin/api/summary','/admin/api/profiles','/admin/api/posts','/admin/api/comments','/admin/api/reports','/admin/api/audit','/admin/api/media/'+id]){const r=await f.request(p,{headers:{Authorization:'Bearer '+game.token}});assert.equal(r.status,401,p);assert.equal(r.headers.get('access-control-allow-origin'),null);assert(!(await r.text()).includes(f.other.username))}
 const wrong=random();f.app.db.prepare('INSERT INTO admin_sessions VALUES(?,?,?,?)').run(random(),hash(wrong),f.other.id,Date.now()+3600000);assert.equal((await f.call('/admin/api/summary',{headers:{Cookie:'__Host-zoigram_admin='+wrong}})).status,401);
 f.app.db.prepare('UPDATE admin_sessions SET expires_at=1 WHERE id=?').run(f.adminId);assert.equal((await f.call('/admin/api/summary')).status,401);
});
test('owner access is explicit, checked on every request and disabled by default',async t=>{
 const f=await fixture(t,{ownerSteamId:''});assert.equal((await f.call('/admin/api/summary')).status,401);assert.equal((await f.request('/admin/auth/password',{method:'POST',headers:{Origin:origin}})).status,503);
 const g=await fixture(t);g.app.db.prepare('UPDATE profiles SET banned=1 WHERE id=?').run(g.owner.id);assert.equal((await g.call('/admin/api/summary')).status,401);
 const h=await fixture(t);h.app.db.prepare('UPDATE profiles SET subject=? WHERE id=?').run('76561198000000009',h.owner.id);assert.equal((await h.call('/admin/api/summary')).status,401);
});
test('CSRF and cross-origin checks prevent mutations and logout does not end the game session',async t=>{
 const f=await fixture(t),game=session(f.app.db,f.owner.id),body={action:'ban',targetId:f.other.id,reason:'Spam'};
 for(const headers of [{'X-CSRF-Token':''},{'X-CSRF-Token':random()},{Origin:'https://evil.example'},{Origin:''},{'Sec-Fetch-Site':'cross-site'}])assert.equal((await f.call('/admin/api/actions',{body,headers})).status,403);
 assert.equal(f.app.db.prepare('SELECT banned FROM profiles WHERE id=?').get(f.other.id).banned,0);assert.equal(f.app.db.prepare('SELECT COUNT(*) n FROM moderation').get().n,0);
 assert.equal((await f.request('/admin/auth/password',{method:'POST',headers:{Origin:'https://evil.example'}})).status,403);
 const out=await f.call('/admin/api/logout',{method:'POST'});assert.equal(out.status,200);assert.equal((await f.call('/admin/api/summary')).status,401);assert(f.app.db.prepare('SELECT 1 FROM sessions WHERE token_hash=?').get(hash(game.token)));
});
test('rename preserves identity and sessions, records the owner, and rejects stale changes',async t=>{
 const f=await fixture(t),game=session(f.app.db,f.other.id),body={action:'set-id',targetId:f.other.id,expectedPublicId:f.other.username,publicId:'new_public_id',reason:'Requested by player',actorId:'forged'};const changed=await f.call('/admin/api/actions',{body});assert.equal(changed.status,200);assert.equal(changed.data.publicId,'new_public_id');assert(f.app.db.prepare('SELECT 1 FROM sessions WHERE token_hash=?').get(hash(game.token)));const audit=(await f.call('/admin/api/audit')).data.items[0];assert.equal(audit.actor.id,f.owner.id);assert.equal(audit.details.previousId,f.other.username);assert.equal(audit.reason,body.reason);
 assert.equal((await f.call('/admin/api/actions',{body:{...body,publicId:'another'}})).status,409);assert.equal((await f.call('/admin/api/actions',{body:{...body,expectedPublicId:'new_public_id',publicId:'with space'}})).status,400);assert.equal(f.app.db.prepare('SELECT COUNT(*) n FROM moderation').get().n,1);
 assert.equal((await f.call('/admin/api/actions',{body:{action:'ban',targetId:f.owner.id,reason:'Mistake'}})).status,403);
});
test('ban revokes game access and unban restores visibility; unchanged actions do not duplicate audit',async t=>{
 const f=await fixture(t),game=session(f.app.db,f.other.id);f.post();const body={action:'ban',targetId:f.other.id,reason:'Repeated spam'};assert.equal((await f.call('/admin/api/actions',{body})).status,200);assert.equal(f.app.db.prepare('SELECT COUNT(*) n FROM sessions WHERE profile_id=?').get(f.other.id).n,0);assert.equal((await f.call('/admin/api/actions',{body})).data.changed,false);assert.equal((await f.request('/api/me',{headers:{Authorization:'Bearer '+game.token}})).status,401);
 assert.equal((await f.call('/admin/api/profiles?status=banned')).data.items.length,1);assert.equal((await f.call('/admin/api/actions',{body:{...body,action:'unban'}})).status,200);assert.equal((await f.call('/admin/api/profiles?status=banned')).data.items.length,0);assert.equal(f.app.db.prepare('SELECT COUNT(*) n FROM moderation').get().n,2);
});
test('deleting reported content is atomic, removes media and reactions, and retains audit context',async t=>{
 const f=await fixture(t),id=f.post(),otherPost=f.post();const db=f.app.db;const cid=Number(db.prepare('INSERT INTO comments(profile_id,post_id,request_id,text,created_at) VALUES(?,?,?,?,?)').run(f.owner.id,id,random(),'A comment',Date.now()).lastInsertRowid);db.prepare('INSERT INTO likes VALUES(?,?)').run(f.owner.id,id);const rid=Number(db.prepare('INSERT INTO reports(profile_id,kind,target_id,reason,created_at) VALUES(?,?,?,?,?)').run(f.owner.id,'post',String(id),'Spam',Date.now()).lastInsertRowid);const body={action:'delete-post',targetId:id,reportId:rid,reason:'Spam confirmed'};
 assert.equal((await f.call('/admin/api/actions',{body:{...body,targetId:otherPost}})).status,409);assert(db.prepare('SELECT 1 FROM posts WHERE id=?').get(otherPost));assert.equal(db.prepare('SELECT COUNT(*) n FROM moderation').get().n,0);
 assert.equal((await f.call('/admin/api/actions',{body})).status,200);assert(!db.prepare('SELECT 1 FROM posts WHERE id=?').get(id));assert(!db.prepare('SELECT 1 FROM comments WHERE id=?').get(cid));assert.equal(db.prepare('SELECT COUNT(*) n FROM likes').get().n,0);assert.equal(db.prepare('SELECT resolved FROM reports WHERE id=?').get(rid).resolved,1);assert.equal((await f.call('/admin/api/media/'+id)).status,404);
 const report=(await f.call('/admin/api/reports?status=closed')).data.items[0];assert.equal(report.target,null);const audit=(await f.call('/admin/api/audit')).data.items[0];assert.equal(audit.details.details.reportId,rid);assert.equal(audit.details.details.profile_id,f.other.id);assert.equal(audit.actor.id,f.owner.id);
 for(const reason of ['', ' ', 'x'.repeat(1001),'two\nlines'])assert.equal((await f.call('/admin/api/actions',{body:{action:'delete-post',targetId:otherPost,reason}})).status,400);assert(db.prepare('SELECT 1 FROM posts WHERE id=?').get(otherPost));
});
test('reports can close and reopen, and lists paginate without dropping equal timestamps',async t=>{
 const f=await fixture(t);for(let i=0;i<28;i++){const p=identity(f.app.db,'test','profile-'+i);f.app.db.prepare('UPDATE profiles SET created_at=1000 WHERE id=?').run(p.id)}const first=(await f.call('/admin/api/profiles')).data;assert.equal(first.items.length,24);assert(first.nextCursor);const second=(await f.call('/admin/api/profiles?before='+first.nextCursor)).data;assert.equal(second.items.length,6);assert.equal(new Set([...first.items,...second.items].map(p=>p.id)).size,30);assert.equal((await f.call('/admin/api/profiles?before=bad')).status,400);
 assert.equal((await f.call('/admin/api/profiles?q='+encodeURIComponent("' OR 1=1 --"))).data.items.length,0);
 const rid=Number(f.app.db.prepare('INSERT INTO reports(profile_id,kind,target_id,reason,created_at) VALUES(?,?,?,?,?)').run(f.owner.id,'profile',f.other.id,'Check account',Date.now()).lastInsertRowid);const body={action:'resolve',targetId:rid,reason:'No violation'};assert.equal((await f.call('/admin/api/actions',{body})).status,200);assert.equal((await f.call('/admin/api/actions',{body})).data.changed,false);assert.equal((await f.call('/admin/api/reports')).data.items.length,0);assert.equal((await f.call('/admin/api/actions',{body:{...body,action:'reopen',reason:'Review again'}})).status,200);assert.equal((await f.call('/admin/api/reports')).data.items.length,1);
});
test('web assets have restrictive CSP and community strings are rendered as text',async t=>{
 const f=await fixture(t);const page=await f.request('/admin/');assert.equal(page.status,200);assert.equal(page.headers.get('x-frame-options'),'DENY');assert(page.headers.get('content-security-policy').includes("script-src 'self'"));assert.equal(page.headers.get('access-control-allow-origin'),null);const source=fs.readFileSync(require('node:path').join(__dirname,'../admin/app.js'),'utf8');new vm.Script(source);assert(!/innerHTML|outerHTML|insertAdjacentHTML|localStorage|document\.cookie|eval\(/.test(source));assert(source.includes('document.createTextNode'));assert(source.includes('node.textContent'));
});
