'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const {openStore,random,hash}=require('../src/store.cjs');const {beginLogin,finishLogin,ENDPOINT}=require('../src/steam.cjs');
const origin='https://zoigram.example';
function setup(t){const db=openStore(':memory:');t.after(()=>db.close());const token=random(),code='ABCDEF1234';db.prepare('INSERT INTO devices(secret_hash,user_code,expires_at) VALUES(?,?,?)').run(hash(token),code,Date.now()+600000);const start=beginLogin(db,origin,code);const redirect=new URL(start.url),ret=redirect.searchParams.get('openid.return_to');const params=new URL(ret).searchParams;for(const [k,v]of Object.entries({ns:'http://specs.openid.net/auth/2.0',mode:'id_res',op_endpoint:ENDPOINT,claimed_id:'https://steamcommunity.com/openid/id/76561198000000001',identity:'https://steamcommunity.com/openid/id/76561198000000001',return_to:ret,response_nonce:new Date().toISOString().replace(/\.\d{3}Z$/,'Z')+random(),signed:'op_endpoint,claimed_id,identity,return_to,response_nonce,assoc_handle',sig:'server-test-signature',assoc_handle:'test'}))params.set('openid.'+k,v);return {db,params,start,token}}
const verified=async(url,opts)=>{assert.equal(url,ENDPOINT);assert.equal(new URLSearchParams(opts.body).get('openid.mode'),'check_authentication');return new Response('ns:http://specs.openid.net/auth/2.0\nis_valid:true\n')};
test('verified Steam assertion links a pending device and cannot be replayed',async t=>{const {db,params,start,token}=setup(t);const id=await finishLogin(db,origin,params,start.cookie,verified);assert.equal(db.prepare('SELECT profile_id FROM devices WHERE secret_hash=?').get(hash(token)).profile_id,id);assert.equal(db.prepare('SELECT provider FROM profiles WHERE id=?').get(id).provider,'steam');await assert.rejects(()=>finishLogin(db,origin,params,start.cookie,verified));});
test('reject forged identities, bad signatures, missing signed fields and login CSRF',async t=>{
 for(const scenario of ['cookie','endpoint','return_to','identity','signed','nonce','signature','duplicate'])await t.test(scenario,async t=>{const {db,params,start}=setup(t);let cookie=start.cookie,fetcher=verified;
  if(scenario==='cookie')cookie=random();if(scenario==='endpoint')params.set('openid.op_endpoint','https://attacker.example');if(scenario==='return_to')params.set('openid.return_to','https://attacker.example');if(scenario==='identity')params.set('openid.claimed_id','https://steamcommunity.com.attacker.example/openid/id/76561198000000001');if(scenario==='signed')params.set('openid.signed','claimed_id');if(scenario==='nonce')params.set('openid.response_nonce','2020-01-01T00:00:00Zexpired');if(scenario==='signature')fetcher=async()=>new Response('is_valid:false\n');if(scenario==='duplicate')params.append('openid.identity',params.get('openid.identity'));
  await assert.rejects(()=>finishLogin(db,origin,params,cookie,fetcher));assert.equal(db.prepare('SELECT COUNT(*) n FROM profiles').get().n,0);
 });
});
