'use strict';
// Russian source messages are stable gettext-style IDs. Never look up player content.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),languages=['ru','en','fr','ko'];
function generate(){
 const rows=JSON.parse(fs.readFileSync(path.join(root,'locales/messages.json'),'utf8')),catalog=Object.fromEntries(languages.map(l=>[l,{}]));
 const placeholders=s=>[...s.matchAll(/\{(\w+)\}/g)].map(m=>m[1]).sort();
 for(const row of rows){assert.equal(row.length,4);assert(!Object.hasOwn(catalog.ru,row[0]),'Duplicate message: '+row[0]);row.forEach((v,i)=>{assert.equal(typeof v,'string');assert(v.trim());assert.deepEqual(placeholders(v),placeholders(row[0]),row[0]);catalog[languages[i]][row[0]]=v})}
 const luaString=s=>'"'+s.replaceAll('\\','\\\\').replaceAll('"','\\"').replaceAll('\n','\\n').replaceAll('\r','\\r')+'"';
 const lua='-- Generated by tools/build-locales.cjs; edit locales/messages.json.\nreturn {\n'+languages.map(l=>' '+l+'={\n'+Object.entries(catalog[l]).map(([k,v])=>'  ['+luaString(k)+']='+luaString(v)+',').join('\n')+'\n },').join('\n')+'\n}\n';
 return {'InzoiSocial/lua/B1/LocalizationCatalog.lua':lua,'server/src/locales.json':JSON.stringify(catalog,null,2)+'\n','InzoiSocial/ui/OnlineBridge/locales.js':'// Generated by tools/build-locales.cjs.\nwindow.ZoigramCatalog='+JSON.stringify(catalog)+';\n'};
}
function build(){const outputs=generate();for(const [file,content]of Object.entries(outputs))fs.writeFileSync(path.join(root,file),content);return outputs}
if(require.main===module){build();console.log('Generated complete ru/en/fr/ko catalogs for Lua, the network bridge and server.')}
module.exports={generate,build,languages};
